### ISSUE TITLE
When the code and benchmark dataset will be released?

### ISSUE THREAD

**Issue by nicezheng** [zhenglab/OceanVP#1]
I really appreciate your efforts in establishing the OceanVP benchmark dataset for comparing DL-based methods.
I notice that this repo is currently empty. Could you please let me know when you plan to release the code and benchmark dataset?
Thanks! ^_^

**Comment by zsshi** [comment]
We have released the data and code of our work. Thanks for your attention, and hope our work will be helpful to you.
